// This file is auto-generated by scripts/generate-version.sh
// Do not edit manually
export const VERSION = {
    git_commit: "50d51581",
    git_describe: "v0.15.2-322-g50d51581-dirty",
    buildTime: "2026-02-17T22:09:48Z",
};
//# sourceMappingURL=version.js.map